name: swipeable_page_route_example
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  swipeable_page_route:
    path: ../

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 281f167123facb724d112ffc84349cf39d8f691f

flutter:
  uses-material-design: true
