name: swipeable_page_route_example
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  swipeable_page_route:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  go_router_builder: ^4.1.0
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 5c5d14476ede3db10f30463ee681f8c547b4ceb2

flutter:
  uses-material-design: true
