name: swipeable_page_route_example
publish_to: none

environment:
  sdk: ^3.6.0-0
  flutter: '>=3.27.0-0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  swipeable_page_route:
    path: ../

dev_dependencies:
  build_runner: ^2.4.10
  go_router_builder: ^2.7.0
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 281f167123facb724d112ffc84349cf39d8f691f

flutter:
  uses-material-design: true
