name: swipeable_page_route
description: Swipe to navigate back and admire beautifully morphing widgets
version: 0.4.8
repository: https://github.com/JonasWanke/swipeable_page_route
screenshots:
  - description: Users can swipe to navigate back anywhere on the page and the app bar transitions beautifully
    path: doc/demo.gif

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  black_hole_flutter: ^1.0.3
  collection: ^1.15.0
  flutter:
    sdk: flutter
  list_diff: ^2.0.0

dev_dependencies:
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 5c5d14476ede3db10f30463ee681f8c547b4ceb2
