name: swipeable_page_route
description: Swipe to navigate back and admire beautifully morphing widgets
version: 0.3.0
repository: https://github.com/JonasWanke/swipeable_page_route
screenshots:
  - description: Users can swipe to navigate back anywhere on the page and the app bar transitions beautifully
    path: doc/demo.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  black_hole_flutter: ^1.0.3
  collection: ^1.15.0
  flutter:
    sdk: flutter
  list_diff: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
